= Flight Service

This service is the same application as the *flight-service* in the https://github.com/jbosstm/quickstart/tree/master/rts/lra[Narayana quickstart] but it is based on Spring Boot.
The REST layer is the same as original so the original *flight-service* can be substituted by this service.
It demonstrates the capability to use LRA in the Spring Boot application.

== How to run

=== Prerequisites

* First, the LRA quickstart repository should be cloned and set up. Following README in that https://github.com/jbosstm/quickstart/tree/master/rts/lra[repo].
* When the LRA quickstart is running, stop the original *flight-service*

=== Start Flight Spring Boot service

* Build and run the *flight-service*

It needs to set ALLOW_ENCODED_SLASH and ALLOW_BACKSLASH to true. Without them, the get endpoint will not work correctly (returns 400 when query param contains encoded slash).

....
mvn clean package
java -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true -Dorg.apache.catalina.connector.CoyoteAdapter.ALLOW_BACKSLASH=true -jar flight-service/target/flight-service-1.0-SNAPSHOT.jar -Dlra.http.port=8081
....

=== Trip reservation

When all services are running, you can do a trip reservation via original LRA quickstart https://github.com/jbosstm/quickstart/tree/master/rts/lra#update-a-trip-booking[client].
....
mvn -f trip-client/pom.xml exec:java -Dservice.http.host="localhost" -Dservice.http.port=8084
....